command_initial = "."
command_tournament = ".torneio"
command_cross_table = ".confronto"
command_cross_table_fix = ". confronto"
command_puzzle = "-puzzle"
command_puzzle_answer = "-a"
command_pgn = ".pgn"
command_pgn_fix = ". pgn"
command_profile = ".perfil"
command_profile_fix = ". perfil"

#Tournaments
command_swiss_tournament = ".swiss"
command_arena_tournament = ".arena"
command_tournament_list_p1 = ".torneio-p1"
command_tournament_list_p2 = ".torneio-p2"
command_tournament_list_p3 = ".torneio-p3"
command_tournament_list_p4 = ".torneio-p4"