#TODO: Translate these strings to your language
text_large_result = "O resultado é muito grande. Tive que gerar um arquivo:"
text_puzzle_command = "Para _Puzzle_ não precisa me mencionar. Pode enviar '_-puzzle_' direto no _Chat_."
text_puzzle_answer_command = "Para responder um _Puzzle_ não precisa me mencionar. Pode enviar '_-a sua resposta_' direto no _Chat_.\n\nTenha em mente de que as anotações de Puzzle estão no formato **global**:\nCavalo = N\nRei = K\nDama = Q\nTorre = R\nBispo = B"
text_bot_mentioned_reply = "Me chamou??\n\nPara falar comigo você precisa me enviar um comando.\n\nVeja a lista de comandos que tenho:\n" + "• _@MrChessBot_ .perfil usuarioLichess -> Mostra as informações gerais de um usuário do Lichess.\n• _@MrChessBot_ .confronto usuarioLichess1, usuarioLichess2 -> Mostra o placar de confrontos entre o 2 jogadores.\n• _@MrChessBot_ .pgn linkPartida -> Ver PGN de uma partida.\n• _@MrChessBot_ linkPartida -> Ver GIF de uma partida.\n• -puzzle -> Solicitar Puzzle para ser resolvido pelo grupo\n• -a respostaPuzzle -> Responder Puzzle enviado anteriormente (Por exemplo: -a Nf3)\n\nAh! Detalhe importante: Não se esquece de que para eu poder responder você, é necessário me mencionar, ok? Para isso basta digitar _@MrChessBot_ e me selecionar.Só não precisa me mencionar quando estiver enviando comandos de _Puzzle_.\n\nOutra coisa: Por enquanto eu só sou integrado na plataforma **Lichess**. Também conto com a ajuda do meu amigo _Lichess Bot_ para fazer os Puzzles. Tenha em mente de que as anotações de Puzzle estão no formato **global**:\nCavalo = N\nRei = K\nDama = Q\nTorre = R\nBispo = B\n\nAté mais o/"
text_no_info_found = "Desculpe, Não consegui achar informações. =/"
text_the_players = "Os jogadores"
text_and = "e"
text_already_played = "já jogaram"
text_result = "Resultado"
text_match_not_found = "Desculpe, não achei a partida. =/"
text_the_player = "O jogador"
text_already_played = "já jogou"
text_matches_on_lichess = "partidas no Lichess"
text_voctories = "Vitórias"
text_loses = "Derrotas"
text_draw = "Empates"
text_classical_matches = "Partidas Clássicas"
text_total_matches_played = "Total de partidas jogadas"
text_profile_lichess = "Seu perfil no Liches é"
text_rapid_matches = "Partidas Rápidas"
text_blitz_matches = "Partidas Blitz"
text_bullet_matches = "Partidas Bullet"
text_correspondence_matches = "Partidas por Correspondência (sem relógio)"